#!/bin/sh

version=6.12.40

depmod ${version}-CRUX

if [ $(command -v dracut) ]; then
	echo "dracut: generating initramfs for kernel $version..."
	dracut --force --kver ${version}-CRUX /boot/initramfs.img
fi
