#!/bin/sh

version=6.12.35

if [ $(command -v dracut) ]; then
	echo "dracut: generating initramfs for kernel $version..."
	dracut --force --kver ${version}-CRUX /boot/initramfs
fi

depmod ${version}-CRUX
